# 1. Разобраться как использовать мультииндексные ключи в данном примере

In [9]:
import numpy as np
import pandas as pd

In [10]:
index = [
    ('city_1', 2010),
    ('city_1', 2020),
    ('city_2', 2010),
    ('city_2', 2020),
    ('city_3', 2010),
    ('city_3', 2020),
]

population = [
    101,
    201,
    102,
    202,
    103,
    203,
]

pop = pd.Series(population, index = index)
pop_df = pd.DataFrame(
    {
        'total': pop,
        'something': [
            10,
            11,
            12,
            13,
            14,
            15,
        ]
    }
)

i = pd.MultiIndex.from_tuples(index)
pop_df = pop_df.reindex(i)
pop_df

             total  something
city_1 2010    101         10
       2020    201         11
city_2 2010    102         12
       2020    202         13
city_3 2010    103         14
       2020    203         15

In [11]:
pop_1 = pop_df.loc['city_2', 'total']
pop_1

2010    102
2020    202
Name: total, dtype: int64

In [12]:
pop_1 = pop_df.loc[['city_2', 'city_3'], ['total', 'something']]
pop_1

             total  something
city_2 2010    102         12
       2020    202         13
city_3 2010    103         14
       2020    203         15

In [13]:
pop_1 = pop_df.loc[['city_1', 'city_2'], 'something']
pop_1

city_1  2010    10
        2020    11
city_2  2010    12
        2020    13
Name: something, dtype: int64

# 2. Из получившихся данных выбрать данные по
# - 2020 году (для всех столбцов)
# - job_1 (для всех строк)
# - для city_1 и job_2

In [ ]:
index = pd.MultiIndex.from_product(
    [
        ['city_1', 'city_2'],
        ['2010', '2020']
    ],
    names=['city', 'year']
)

columns = pd.MultiIndex.from_product(
    [
        ['person_1', 'person_2', 'person_3'],
        ['job_1', 'job_2']
    ],
    names=['worker', 'job']
)

rng = np.random.default_rng(1)
data_r = rng.random((4, 6))

data = pd.DataFrame(data_r, index=index, columns=columns)
data

In [ ]:
data_1 = data.xs('2020', level='year')
data_1

In [ ]:
data_1 = data.xs('job_1', level='job', axis=1)
data_1

In [ ]:
data_city = data.xs('city_1', level='city')
data_1 = data_city.xs('job_2', level='job', axis=1)
data_1

# 3. Выполнить запрос на получение следующих данных
# - все данные по person_1 и person_3
# - все данные по первому городу и первым двум person-ам (с использование срезов)

In [ ]:
data_1 = data.loc[:, ['person_1', 'person_3']]
data_1

In [ ]:
data_1 = data.loc['city_1', pd.IndexSlice['person_1':'person_2']]
data_1

In [ ]:
data_1 = data.loc[pd.IndexSlice[:, '2020'], pd.IndexSlice['person_1':'person_2']]
data_1

# 4. Привести пример использования inner и outer джойнов для Series

In [15]:
ser1 = pd.Series(['1', '2', '3'], index=[1, 2, 3])
ser2 = pd.Series(['1', '2', '3'], index=[1, 0, 3])

outer_join = pd.concat([ser1, ser2], axis=1, join="outer")
print(outer_join)

inner_join = pd.concat([ser1, ser2], axis=1, join="inner")
print(inner_join)

     0    1
1    1    1
2    2  NaN
3    3    3
0  NaN    2
   0  1
1  1  1
3  3  3